### ISSUE TITLE
pywayland.protocol_core.resource._post_event() error

### ISSUE THREAD

**Issue by green-green-avk** [flacjacket/pywayland#17]
```
From cffi callback <function global_bind_func at 0x79ca3e9840>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pywayland/protocol_core/globals.py", line 35, in global_bind_func
    callback_info["bind_func"](resource)
  File "./wayland", line 21, in onBindOutput
    WlOutput.transform.normal
  File "/usr/local/lib/python3.7/dist-packages/pywayland/protocol/wayland/wl_output.py", line 140, in geometry
    self._post_event(0, x, y, physical_width, physical_height, subpixel, make, model, transform)
  File "/usr/local/lib/python3.7/dist-packages/pywayland/utils.py", line 28, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pywayland/protocol_core/resource.py", line 87, in _post_event
    args_ptr = self._interface.events[opcode].arguments_to_c(*args)
AttributeError: 'WlOutputResource' object has no attribute '_interface'
```
<https://github.com/flacjacket/pywayland/blob/65aae61d5df320dc0c39d46761e44a4e34137bb2/pywayland/protocol_core/resource.py#L87>
Misprint? (It seems, it should be `self.interface`.)

**Comment by green-green-avk** [comment]
<https://github.com/flacjacket/pywayland/pull/18>
