### ISSUE TITLE
pywayland-scanner throws KeyError 'wl_surface'

### ISSUE THREAD

**Issue by heuer** [flacjacket/pywayland#58]
I fixed the import error from issue #57 locally, but now I get another error:

```
pywayland-scanner -i wlr-layer-shell-unstable-v1.xml
Traceback (most recent call last):
  File "/home/user/pywayland-test/bin/pywayland-scanner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/pywayland-test/lib/python3.11/site-packages/pywayland/scanner/__main__.py", line 117, in main
    protocol.output(args.output_dir, protocol_imports)
  File "/home/user/pywayland-test/lib/python3.11/site-packages/pywayland/scanner/protocol.py", line 109, in output
    iface.output(printer, module_imports)
  File "/home/user/pywayland-test/lib/python3.11/site-packages/pywayland/scanner/interface.py", line 67, in output
    imports = set(
              ^^^^
  File "/home/user/pywayland-test/lib/python3.11/site-packages/pywayland/scanner/interface.py", line 70, in <genexpr>
    for _import in method.imports(self.name, module_imports)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/pywayland-test/lib/python3.11/site-packages/pywayland/scanner/method.py", line 64, in imports
    import_protocol = module_imports[arg.interface]
                      ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'wl_surface'
```

**Comment by Jamim** [comment]
_Hello @flacjacket,_
It would be great to have some guidance here.
_Thanks in advance!_

**Comment by knirch** [comment]
Couldn't wrap my head around this either. But it seems that `-i` has a default value, and is also noted in the source to be special?

https://github.com/flacjacket/pywayland/blob/7f48c575076b3e620a6ba3565dc877d3a9e665ff/pywayland/scanner/__main__.py#L114

Now, I don't know anything about any of this, but if `-i` is not provided, it's populated by https://github.com/flacjacket/pywayland/blob/7f48c575076b3e620a6ba3565dc877d3a9e665ff/pywayland/scanner/__main__.py#L63-L69

anyway, the workaround(or proper way?) is to do what the code seems to want. Add wayland.xml.

(and don't do what I did, it's `-i file.xml otherfile.xml` not `-i file.xml` `-i otherfile.xml`)

So for me attempting to process `wlr-layer-shell-unstable-v1.xml` what works is
```sh
$ uv run pywayland-scanner \
  -o TEST \
  --with-protocols \
  -i /usr/share/wayland/wayland.xml \
    ./wlr-layer-shell-unstable-v1.xml

alt

$ uv run pywayland-scanner \
  -o TEST \
  -i /usr/share/wayland/wayland.xml \
    /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
    ./wlr-layer-shell-unstable-v1.xml
``` 
I'm half assuming I'm doing it all wrong, but it seems to work. Assumption is that a correct workflow would have all the files in a proper place etc. Kind of like this (?)
```sh
$ cp -r /usr/share/wayland-protocols testing
$ cp wlr-layer-shell-unstable-v1.xml testing/unstable/
$ uv run pywayland-scanner --input-protocols $PWD/testing --with-protocols -o FOO
$ echo FOO/*layer*
FOO/wlr_layer_shell_unstable_v1.py
```

IDK. I assume we held it wrong, and it works as intended. And that this is all very painful to people not terminally confused. :)
